# Generated by Django 5.2.3 on 2025-06-28 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('user_id', models.BigIntegerField(help_text='Unique Telegram user ID.', primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(blank=True, help_text="Telegram user's first name.", max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, help_text="Telegram user's last name.", max_length=255, null=True)),
                ('username', models.CharField(blank=True, help_text="Telegram user's username (if set).", max_length=255, null=True)),
                ('is_bot', models.BooleanField(default=False, help_text='True if this Telegram user is a bot.')),
                ('language_code', models.CharField(blank=True, help_text='Language code of the Telegram client.', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_custom_user', models.OneToOneField(blank=True, help_text='The CustomUser account linked to this Telegram profile.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
            },
        ),
        migrations.CreateModel(
            name='BotInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(blank=True, help_text='The text of the incoming message or command.', null=True)),
                ('command_used', models.CharField(blank=True, help_text='The specific command used (e.g., /start, /help).', max_length=100, null=True)),
                ('response_text', models.TextField(blank=True, help_text="The text of the bot's response.", null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the interaction.')),
                ('telegram_user', models.ForeignKey(help_text='The Telegram user involved in this interaction.', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='telegram.telegramuser')),
            ],
            options={
                'verbose_name': 'Bot Interaction Log',
                'verbose_name_plural': 'Bot Interaction Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
